src/baking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("machine_not_free/", views.make_recipe, name="machine_not_free"),
    path("make_recipe/<int:recipe_id>/", views.make_recipe, name="make_recipe"),
]

src/inventory_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing_pages.urls")),
    path("", include("baking.urls")),
    path("", include("registration.urls")),
    path("", include("django.contrib.auth.urls"))
]

src/landing_pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_page, name = "home_page"),
    path("recipes/", views.recipe_page, name = "recipe_page"),
    path("recipes/edit/<int:recipe_id>/", views.edit_recipe, name = "edit_recipe"),
    path("recipes/delete/<int:recipe_id>/", views.delete_recipe, name = "delete_recipe"),
    path("recipes/view/<int:recipe_id>/", views.view_recipe_ingredients, name="view_recipe_ingredients"),
    path("inventory/", views.inventory_page, name = "inventory_page"),
    path("machines/", views.machine_page, name = "machine_page"),
    path("machines/edit/<int:machine_id>/", views.edit_machine, name = "edit_machine"),
    path("machines/delete/<int:machine_id>/", views.delete_machine, name = "delete_machine"),
    path("inventory/edit/<int:ingredient_id>/", views.edit_ingredient, name = "edit_ingredient"),
    path("inventory/delete/<int:ingredient_id>/", views.delete_ingredient, name = "delete_ingredient"),
    path("baking_log/", views.baking_log, name="baking_log"),
]

src/landing_pages/models.py
from django.db import models
from django.contrib.auth.models import User


class Recipes(models.Model):
    recipe_name = models.CharField(max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    machine = models.ForeignKey("Machines", on_delete=models.SET(None), null=True, default=None)
    machine_duration = models.DurationField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)

    def __str__(self):
        return self.recipe_name
    

    
class Ingredients(models.Model):
    ingredient_name = models.CharField(max_length=500)
    stock_quantity = models.IntegerField(default=0)
    unit = models.CharField(max_length=100)

    def __str__(self):
        return self.ingredient_name
    

    
class Recipes_Ingredients(models.Model):
    recipe = models.ForeignKey("Recipes", on_delete=models.CASCADE)
    ingredient = models.ForeignKey("Ingredients", on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        unique_together = ["recipe", "ingredient"]

    def __str__(self):
        return f"{self.quantity} {self.ingredient.unit} of {self.ingredient.ingredient_name} in {self.recipe.recipe_name}"
    

    
class Machines(models.Model):
    # Tuple contains value stored in database and human-readable name
    status_choices = [("In use", "In use"), ("Free", "Free")]

    machine_name = models.CharField(max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=status_choices, default="Free")
    remaining_time = models.FloatField(default=0.0)
    last_used = models.DateTimeField(null=True, blank=True)
    machine_type = models.CharField(max_length=500)

    def __str__(self):
        return self.machine_name


    
class Recipe_Log(models.Model):
    recipe = models.ForeignKey("Recipes", on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)



class Products(models.Model):
    status_choices = [("Fresh", "Fresh"), ("Expired", "Expired")]
    recipe = models.ForeignKey("Recipes", on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateTimeField()
    status = models.CharField(max_length=10, choices=status_choices, default="Fresh")

src/landing_pages/forms.py
from django import forms
from .models import Recipes, Machines, Ingredients, Recipes_Ingredients

class RecipesModelForm(forms.ModelForm):
    machine_duration = forms.DurationField(
        required=False,
        help_text="Enter duration in seconds (e.g. 30 for 30 seconds)",
        widget=forms.NumberInput(attrs={'step': 'any'}),
    )
    class Meta:
        model = Recipes
        fields = ["recipe_name", "machine", "machine_duration"]
        labels = {
            "recipe_name": "Recipe",
            "machine": "Machine",
            "machine_duration": "Duration"
        }

class MachinesModelForm(forms.ModelForm):
    class Meta:
        model = Machines
        fields = ["machine_name", "machine_type"]


class IngredientsModelForm(forms.ModelForm):
    class Meta:
        model = Ingredients
        fields = ["ingredient_name", "stock_quantity", "unit"]
        labels = {
            "ingredient_name": "Ingredient",
            "stock_quantity": "Quantity",
            "unit": "Unit"
        }

class RecipesIngredientsModelForm(forms.ModelForm):
    ingredient = forms.ModelChoiceField(queryset=Ingredients.objects.all())
    class Meta:
        model = Recipes_Ingredients
        fields = ["ingredient", "quantity"]

src/landing_pages/views/inventory_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from ..models import Ingredients, Products
from ..forms import IngredientsModelForm

@login_required(login_url="/login")
def inventory_page(request):
    # Fetches all the entries in the Ingredients and Products table
    ingredients = Ingredients.objects.all() 
    products = Products.objects.all()

    product_dict = {}

    for product in products:
        if product not in product_dict:
            product_dict.setdefault(product.recipe, 0)
        product_dict[product.recipe] += 1

    if request.method == "POST":
        form = IngredientsModelForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("inventory_page")
    
    else:
        form = IngredientsModelForm()

    title = "Inventory"
    context = {
        "ingredients" : ingredients,
        "product_dict": product_dict,
        "form": form,
        "title": title
    }

    print(product_dict)

    return render(request, "landing_pages/inventory.html", context)


@login_required(login_url="/login")
def edit_ingredient(request, ingredient_id):
    ingredient = get_object_or_404(Ingredients, id=ingredient_id)
    form = IngredientsModelForm(instance=ingredient)

    if request.method == "POST":
        form = IngredientsModelForm(request.POST, instance=ingredient)
        if form.is_valid():
            form.save()
            return redirect("inventory_page")
        
    context = {
        "form": form,
        "title": "Edit Ingredient"
    }

    return render(request, "landing_pages/edit_ingredient.html", context)

@login_required(login_url="/login")
def delete_ingredient(request, ingredient_id):
    ingredient = get_object_or_404(Ingredients, id=ingredient_id)
    if request.method == "POST":
        ingredient.delete()
        return redirect("inventory_page")
    
    context = {
        "ingredient": ingredient,
        "title": "Delete Ingredient"
    }

    return render(request, "landing_pages/delete_ingredient.html", context)

src/landing_pages/views/machine_views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import timedelta
from django.contrib.auth.decorators import login_required

from ..models import Machines, Recipes
from ..forms import MachinesModelForm

@login_required(login_url="/login")
def machine_page(request):
    machines = Machines.objects.all()
    # test = Recipe_Machines.objects.get(pk=1)

    if request.method == "POST":
        form = MachinesModelForm(request.POST)

        if form.is_valid():
            form.save()
        return redirect("machine_page")
    
    else:
        form = MachinesModelForm()

    title = "Machines"
    context = {
        "machines": machines,
        "form": form,
        "title": title,
    }

    return render(request, "landing_pages/machines.html", context)


@login_required(login_url="/login")
def edit_machine(request, machine_id):
    machine = get_object_or_404(Machines, id=machine_id)
    form = MachinesModelForm(instance=machine)

    if request.method == "POST":
        form = MachinesModelForm(request.POST, instance=machine)
        if form.is_valid():
            form.save()
            return redirect("machine_page")
        
    context = {
        "form": form,
        "title": "Edit Machine"
    }

    return render(request, "landing_pages/edit_machine.html", context)


@login_required(login_url="/login")
def delete_machine(request, machine_id):
    machine = get_object_or_404(Machines, id=machine_id)

    if request.method == "POST":
        # Update related Recipes' machine_duration to zero
        Recipes.objects.filter(machine=machine_id).update(machine_duration=timedelta())
        machine.delete()

        return redirect("machine_page")
    
    context = {
        "machine": machine,
        "title" : "Delete Machine"
    }

    return render(request, "landing_pages/delete_machine.html", context)

src/landing_pages/views/recipe_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required

from ..models import Recipes, Ingredients, Recipes_Ingredients, Machines, Recipe_Log
from ..forms import RecipesModelForm, RecipesIngredientsModelForm

# If not logged in, redirect to /login
@login_required(login_url="/login")
def home_page(request):
    title = "Inventory Tracker Home Page"
    welcome_message = "Welcome to the Inventory Tracker Home Page"
    recipes = Recipes.objects.all()
    machines = Machines.objects.all()
    context = {
        "title" : title,
        "welcome": welcome_message,
        "recipes": recipes,
        "machines": machines,
    }
    return render(request, "landing_pages/home.html", context)



@login_required(login_url="/login")
def recipe_page(request):
    recipes = Recipes.objects.all() # Fetches all the entries in the Recipes table

    if request.method == "POST":
        recipe_form = RecipesModelForm(request.POST) # Creates form instance with the submitted POST data
        ingredients_formset = formset_factory(RecipesIngredientsModelForm, extra=3)

        if recipe_form.is_valid():
            recipe = recipe_form.save()
            formset = ingredients_formset(request.POST)

            if formset.is_valid():
                for form in formset:
                    ingredient = form.cleaned_data.get('ingredient')
                    quantity = form.cleaned_data.get('quantity')
                    Recipes_Ingredients.objects.create(recipe=recipe, ingredient=ingredient, quantity=quantity)

                return redirect("recipe_page")
            
            else:
                print(formset.errors)
            

    else:
        recipe_form = RecipesModelForm()
        ingredients_formset = formset_factory(RecipesIngredientsModelForm, extra=3)
        formset = ingredients_formset()

    title = "Recipes"
    context = {
        "recipes" : recipes,
        "recipe_form": recipe_form,
        "formset": formset,
        "title": title
    }

    return render(request, "landing_pages/recipes.html", context)



@login_required(login_url="/login")
def edit_recipe(request, recipe_id):
    # Retrieve the recipe object with the specified recipe_id from the database.
    # If the object does not exist, it returns a 404 page.
    recipe = get_object_or_404(Recipes, id=recipe_id)
    form = RecipesModelForm(instance=recipe)

    # Check if the form is submitted via POST
    if request.method == "POST":
        # Create a form instance with the submitted POST data and the existing recipe data
        form = RecipesModelForm(request.POST, instance=recipe)
        # Check if the form is valid
        if form.is_valid():
            # Save the form data to update the existing recipe in the database
            form.save()
            return redirect("recipe_page")

    context = {
        "form": form,
        "title": "Edit Recipe"
    }

    return render(request, "landing_pages/edit_recipe.html", context)


@login_required(login_url="/login")
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipes, id=recipe_id)

    if request.method == "POST":
        recipe.delete()
        return redirect("recipe_page")
    
    context = {
        "recipe": recipe,
        "title": "Delete Recipe"
    }

    return render(request, "landing_pages/delete_recipe.html", context)

@login_required(login_url="/login")
def view_recipe_ingredients(request, recipe_id):
    recipe = get_object_or_404(Recipes, id=recipe_id)
    ingredients = Recipes_Ingredients.objects.filter(recipe=recipe)
    
    context = {
        "recipe": recipe,
        "ingredients": ingredients,
        "title": f"Ingredients for {recipe.recipe_name}"
    }
    return render(request, "landing_pages/view_recipe_ingredients.html", context)

@login_required(login_url="/login")
def baking_log(request):
    logs = Recipe_Log.objects.all()
    title = "Baking Log"
    context = {
        "logs": logs,
        "title": title
    }

    return render(request, "landing_pages/baking_log.html", context)

src/templates/landing_pages/baking_log.html
<!-- Inherits from base.html (parent template) -->
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}


{% block content %}
<h1>Baking Log</h1>

<!-- Display existing recipes in a table -->
<table class="table">
   <thead>
       <tr>
           <th scope="col">#</th>
           <th scope="col">Recipe</th>
           <th scope="col">Timestamp</th>
       </tr>
   </thead>
   <tbody>
       {% for log in logs %}
           <tr>
               <th scope="row">{{ forloop.counter }}</th>
               <td>{{ log.recipe }}</td>
               <td>{{ log.timestamp|date:"F d, Y H:i" }}</td>
           </tr>
       {% endfor %}
   </tbody>
</table>
{% endblock %}

src/templates/landing_pages/delete_ingredient.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Delete Ingredient</h1>
    <p>Are you sure you want to delete "{{ ingredient.ingredient_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

src/templates/landing_pages/delete_machine.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Delete Machine</h1>
    <p>Are you sure you want to delete "{{ machine.machine_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

src/templates/landing_pages/delete_recipe.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Delete Recipe</h1>
    <p>Are you sure you want to delete "{{ recipe.recipe_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

src/templates/landing_pages/edit_ingredient.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Edit Ingredient</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save Changes</button>
    </form>
{% endblock %}

src/templates/landing_pages/edit_machine.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Edit Machine</h1>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="input-group mb-3">
                <span class="input-group-text" style="min-width: 140px;">{{ field.label_tag }}</span>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Save Changes</button>
    </form>
{% endblock %}

src/templates/landing_pages/edit_recipe.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Edit Recipe</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save Changes</button>
    </form>
{% endblock %}

src/templates/landing_pages/home.html
 <!-- Inherits from base.html (parent template) -->
 {% extends "base.html" %}

 {% block title %}
 {{ title }}
 {% endblock %}
 
 {% block content %}
 <h1>{{ welcome }}</h1>
 <div class="d-flex flex-wrap gap-2" style="margin-bottom: 20px;">
    {% for recipe in recipes %}
        <form action="{% url 'make_recipe' recipe.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" style="width: 180px; height: 80px;">Make {{ recipe }}</button>
        </form>
    {% endfor %}
</div>
<div class="d-flex flex-wrap gap-2">
    {% for machine in machines %}
    {% if machine.status == "Free" %}
    <div class="card border border-success border-3" style="width: 18rem;">
    {% else %}
    <div class="card border border-danger border-3" style="width: 18rem;">
    {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ machine.machine_name }}</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{ machine.status }}</h6>
          <p class="card-text">{{ machine.machine_type }}</p>
        </div>
    </div>
    {% endfor %}
</div>

 {% endblock %}

src/templates/landing_pages/inventory.html
 <!-- Inherits from base.html (parent template) -->
 {% extends "base.html" %}

 {% block title %}
 {{ title }}
 {% endblock %}
 

{% block content %}
<h1>Inventory</h1>
<h2>Ingredients</h2>
<!-- Display ingredients in a table -->
<table class="table">
    <thead>
        <tr>
            <th scope="col">Ingredient Name</th>
            <th scope="col">Quantity in stock</th>
            <th scope="col">Unit</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for ingredient in ingredients %}
            <tr>
                <td>{{ ingredient.ingredient_name }}</td>
                <td>{{ ingredient.stock_quantity }}</td>
                <td>{{ ingredient.unit }}</td>
                <td>
                    {% if perms.landing_pages.change_ingredients %}
                    <a href="{% url 'edit_ingredient' ingredient.id %}">Edit</a>
                    {% endif %}
                    {% if perms.landing_pages.delete_ingredients %}
                    <a href="{% url 'delete_ingredient' ingredient.id %}">Delete</a>
                    {% endif %}
                </td>
                
            </tr>
        {% endfor %}
    </tbody>
</table>

{% if perms.landing_pages.add_ingredients %}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="input-group mb-3">
            <span class="input-group-text" style="min-width: 120px;">{{ field.label_tag }}</span>
            {{ field }}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success" style="margin-bottom: 20px;">Add Ingredient</button>
</form>
{% endif %}

<h2>Products</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Product</th>
            <th scope="col">Quantity in stock</th>
        </tr>
    </thead>
    <tbody>
        {% for product, quantity in product_dict.items %}
            <tr>
                <td>{{ product }}</td>
                <td>{{ quantity }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

src/templates/landing_pages/machines.html
<!-- Inherits from base.html (parent template) -->
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<h1>Machines</h1>
<!-- Display existing recipes in a table -->
<table class="table">
    <thead>
        <tr>
            <th scope="col">Machine Name</th>
            <th scope="col">Machine Type</th>
            <th scope="col">Status</th>
            <th scope="col">Date added</th>
            <th scope="col">Last updated</th>
            <th scope="col">Actions</th>
    </thead>
    <tbody>
        {% for machine in machines %}
            <tr>
                <td>{{ machine.machine_name }}</td>
                <td>{{ machine.machine_type }}</td>
                <td>{{ machine.status }}</td>
                <td>{{ machine.timestamp|date:"F d, Y H:i" }}</td>
                <td>{{ machine.updated|date:"F d, Y H:i" }}</td>
                <td>
                    {% if perms.landing_pages.change_machines %}
                    <a href="{% url 'edit_machine' machine.id %}">Edit</a>
                    {% endif %}
                    {% if perms.landing_pages.delete_machines %}
                    <a href="{% url 'delete_machine' machine.id %}">Delete</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% if perms.landing_pages.add_machines %}
<!-- Form for adding new recipes or editing existing recipes -->
<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="input-group mb-3">
            <span class="input-group-text" style="min-width: 140px;">{{ field.label_tag }}</span>
            {{ field }}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Add Machine</button>
</form>
{% endif %}
{% endblock %}

src/templates/landing_pages/recipes.html
 <!-- Inherits from base.html (parent template) -->
 {% extends "base.html" %}

 {% block title %}
 {{ title }}
 {% endblock %}
 

{% block content %}
<h1>Recipes</h1>

<!-- Display existing recipes in a table -->
<table class="table">
    <thead>
        <tr>
            <th scope="col">Recipe Name</th>
            <th scope="col">Machine</th>
            <th scope="col">Duration</th>       
            <th scope="col">Date added</th>
            <th scope="col">Last updated</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for recipe in recipes %}
            <tr>
                <td>{{ recipe.recipe_name }}</td>
                <td>{{ recipe.machine }}</td>
                <td>{{ recipe.machine_duration }}</td>
                <td>{{ recipe.timestamp|date:"F d, Y H:i" }}</td>
                <td>{{ recipe.updated|date:"F d, Y H:i" }}</td>
                <td>
                    <a href="{% url 'view_recipe_ingredients' recipe.id %}">View Ingredients</a>
                    {% if perms.landing_pages.change_recipes %}
                    <a href="{% url 'edit_recipe' recipe.id %}">Edit</a>
                    {% endif %}
                    {% if perms.landing_pages.delete_recipes %}
                    <a href="{% url 'delete_recipe' recipe.id %}">Delete</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Form for adding new recipes or editing existing recipes -->
{% if perms.landing_pages.add_recipes %}
<form method="post" action="{% url 'recipe_page' %}">
    {% csrf_token %}
    {% for field in recipe_form %}
        <div class="input-group mb-3">
            <span class="input-group-text" style="min-width: 120px;">{{ field.label_tag }}</span>
            {{ field }}
        </div>
    {% endfor %}
    {% for form in formset %}
        <div class="row-m3">
            {% for element in form %}
                <div class="input-group">
                    <span class="input-group-text" style="min-width: 120px;">{{ element.label_tag }}</span>
                    {{ element }}
                </div>
            {% endfor %}
        </div>
    {% endfor %}

    <button type="submit" class="btn btn-success">Add Recipe</button>
</form>
{% endif %}
{% endblock %}

src/templates/landing_pages/view_recipe_ingredients.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Ingredients for {{ recipe.recipe_name }}:</p>
    <ul>
        {% for ingredient in ingredients %}
            <li>{{ ingredient.quantity }} {{ ingredient.ingredient.unit }} of {{ ingredient.ingredient.ingredient_name }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'recipe_page' %}">Back to Recipes</a>
{% endblock %}